# skill_1, skill2, skill_3, skill_4, skill_5 = Skill.create([
#                                                               {name: 'CSS3'},
#                                                               {name: 'Проектирование'},
#                                                               {name: 'Ruby-On-Rails'},
#                                                               {name: 'Capistrano'},
#                                                               {name: 'Agile Scrum'}
#                                                           ])
#
# Vacancy.create([
#                    {name: 'Web-разработчик',
#                     available_to: 7.days.from_now,
#                     salary: 95000,
#                     email: 'vacancy1@example.com',
#                     phone: '+7(495)111-1111',
#                     skills: [skill_1, skill_2, skill_5]},
#                    {name: 'Программист-верстальщик',
#                     available_to: 7.days.from_now,
#                     salary: 50000,
#                     email: nil,
#                     phone: '+7(495)222-2222',
#                     skills: [skill_1, skill_5]},
#                    {name: 'Администратор сайта',
#                     available_to: 14.days.from_now,
#                     salary: 100000,
#                     email: 'vacancy3@example.com',
#                     phone: nil,
#                     skills: [skill_3, skill_4]},
#                    {name: 'Разработчик Ruby on Rails',
#                     available_to: 7.days.from_now,
#                     salary: 60000,
#                     email: nil,
#                     phone: '+7(495)444-4444',
#                     skills: [skill_3, skill_4, skill_5]},
#                    {name: 'Backend разработчик',
#                     available_to: 10.days.from_now,
#                     salary: 120000,
#                     email: 'vacancy5@example.com',
#                     phone: '+7(495)555-5555',
#                     skills: [skill_2, skill_3, skill_4]},
#                    {name: 'Системный администратор',
#                     available_to: 21.days.from_now,
#                     salary: 100000,
#                     email: nil,
#                     phone: '+7(495)666-6666',
#                     skills: [skill_2, skill_4]},
#                    {name: 'DevOps Инженер',
#                     available_to: 1.days.ago,
#                     salary: 110000,
#                     email: 'vacancy7@example.com',
#                     phone: nil,
#                     skills: [skill_2, skill_3, skill_4, skill_5]},
#                    {name: 'Ведущий программист',
#                     available_to: 7.days.from_now,
#                     salary: 150000,
#                     email: nil,
#                     phone: '+7(495)888-8888',
#                     skills: [[skill_1, skill_2, skill_3, skill_4, skill_5]]},
#                    {name: 'CI Engineer',
#                     available_to: 1.days.ago,
#                     salary: 80000,
#                     email: 'vacancy9@example.com',
#                     phone: nil,
#                     skills: [skill_4]},
#                    {name: 'Разработчик-автоматизатор',
#                     available_to: 14.days.from_now,
#                     salary: 130000,
#                     email: nil,
#                     phone: '+7(495)1234567',
#                     skills: [skill_2, skill_3]}
#                ])

# Applicant.create([
#                      {name: '',
#                       email: 'applicant1@example.com',
#                       phone: '+7(495)7654321',
#                       is_active: 1,
#                       salary: 100000,
#                       skills: []},
#                      {name: '',
#                       email: 'applicant1@example.com',
#                       phone: '+7(495)7654321',
#                       is_active: 1,
#                       salary: 100000,
#                       skills: []},
#                      {name: '',
#                       email: 'applicant1@example.com',
#                       phone: '+7(495)7654321',
#                       is_active: 1,
#                       salary: 100000,
#                       skills: []},
#                      {name: '',
#                       email: 'applicant1@example.com',
#                       phone: '+7(495)7654321',
#                       is_active: 1,
#                       salary: 100000,
#                       skills: []},
#                      {name: '',
#                       email: 'applicant1@example.com',
#                       phone: '+7(495)7654321',
#                       is_active: 1,
#                       salary: 100000,
#                       skills: []},
#                      {name: '',
#                       email: 'applicant1@example.com',
#                       phone: '+7(495)7654321',
#                       is_active: 1,
#                       salary: 100000,
#                       skills: []},
#                      {name: '',
#                       email: 'applicant1@example.com',
#                       phone: '+7(495)7654321',
#                       is_active: 1,
#                       salary: 100000,
#                       skills: []},
#                      {name: '',
#                       email: 'applicant1@example.com',
#                       phone: '+7(495)7654321',
#                       is_active: 1,
#                       salary: 100000,
#                       skills: []},
#                      {name: '',
#                       email: 'applicant1@example.com',
#                       phone: '+7(495)7654321',
#                       is_active: 1,
#                       salary: 100000,
#                       skills: []},
#                      {name: '',
#                       email: 'applicant1@example.com',
#                       phone: '+7(495)7654321',
#                       is_active: 1,
#                       salary: 100000,
#                       skills: []}
#                ])
